dist: trusty
language: minimal
#go:
#- "1.11"

cache:
  directories:
    - $HOME/bazel/install
    - $HOME/bazel/outbase

before_install:
- |
  URL="https://github.com/bazelbuild/bazel/releases/download/${V}/bazel-${V}-installer-${OS}-x86_64.sh"
  wget -O install.sh "${URL}"
  chmod +x install.sh
  ./install.sh --user

script:
  - make docker-build
  - make docker-run

env:
  global:
  - V=0.22.0
  - OS=linux
