dist: trusty
language: minimal

cache:
  directories:
    - $HOME/bazel/output/external
    - $HOME/bazel/repository_cache

before_install:
- |
  URL="https://github.com/bazelbuild/bazel/releases/download/${V}/bazel-${V}-installer-${OS}-x86_64.sh"
  wget -O install.sh "${URL}"
  chmod +x install.sh
  ./install.sh --user

script:
  - make bazel-test
  - make bazel-build

env:
  global:
  - V=0.24.0
  - OS=linux
